[project]
name = "lead-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "advanced-alchemy>=1.8.2",
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "extra-streamlit-components>=0.1.81",
    "fastapi>=0.119.0",
    "litestar>=2.19.0",
    "loguru>=0.7.3",
    "pandas>=2.2.0",
    "plotly>=5.24.0",
    "psycopg2-binary>=2.9.9",
    "pydantic-settings>=2.12.0",
    "skuf>=0.2.1",
    "sqlalchemy>=2.0.43",
    "streamlit>=1.40.0",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.13.3",
]

[tool.pytest.ini_options]
addopts = "-xs"
pythonpath = ["src"]


[tool.alembic]
script_location = "%(here)s/src/database/migration"
prepend_sys_path = [
    ".",
    "src"
]
