"""add cascade delete to user_bot_accounts user_id fk

Revision ID: 05fb0aa51d37
Revises: c3d4e5f6a7b8
Create Date: 2026-02-06 15:46:16.436785

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "05fb0aa51d37"
down_revision: Union[str, None] = "c3d4e5f6a7b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_bot_accounts_user_id_fkey"), "user_bot_accounts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("user_bot_accounts_user_id_fkey"),
        "user_bot_accounts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("user_bot_accounts_user_id_fkey"), "user_bot_accounts", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("user_bot_accounts_user_id_fkey"),
        "user_bot_accounts",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
