"""add missing indexes for source_account_id

Revision ID: 4c5929d26261
Revises: fca310fdf37f
Create Date: 2026-02-05 13:53:37.934156

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4c5929d26261"
down_revision: Union[str, None] = "fca310fdf37f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_payments_source_account_id"),
        "payments",
        ["source_account_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_users_source_account_id"),
        "users",
        ["source_account_id"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Индексы были изначально созданы в fca310fdf37f.
    # Этот upgrade использовал if_not_exists=True (no-op если уже есть),
    # поэтому downgrade не должен их удалять.
    pass
