"""add bot_username to bot_accounts

Revision ID: 5d490abdc3a2
Revises: 4c5929d26261
Create Date: 2026-02-05 13:54:10.816920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d490abdc3a2'
down_revision: Union[str, None] = '4c5929d26261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_accounts', sa.Column('bot_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_accounts', 'bot_username')
    # ### end Alembic commands ###
