"""add bot_accounts table and source_account_id

Revision ID: fca310fdf37f
Revises: 55fd4e9dcbe3
Create Date: 2026-02-04 12:57:34.495812

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fca310fdf37f"
down_revision: str | None = "55fd4e9dcbe3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.BIGINT(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("chat_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id"),
    )
    op.add_column("payments", sa.Column("source_account_id", sa.UUID(), nullable=True))
    op.create_index("ix_payments_source_account_id", "payments", ["source_account_id"])
    op.create_foreign_key(
        "payments_source_account_id_fkey",
        "payments",
        "bot_accounts",
        ["source_account_id"],
        ["id"],
    )
    op.add_column("users", sa.Column("source_account_id", sa.UUID(), nullable=True))
    op.create_index("ix_users_source_account_id", "users", ["source_account_id"])
    op.create_foreign_key(
        "users_source_account_id_fkey",
        "users",
        "bot_accounts",
        ["source_account_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_source_account_id_fkey", "users", type_="foreignkey")
    op.drop_index("ix_users_source_account_id", "users")
    op.drop_column("users", "source_account_id")
    op.drop_constraint(
        "payments_source_account_id_fkey", "payments", type_="foreignkey"
    )
    op.drop_index("ix_payments_source_account_id", "payments")
    op.drop_column("payments", "source_account_id")
    op.drop_table("bot_accounts")
    # ### end Alembic commands ###
